// <auto-generated />
using System;
using C4_ChauSolution.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace C4_ChauSolution.Migrations
{
    [DbContext(typeof(VatLieuDbContext))]
    [Migration("20230320175145_add_db")]
    partial class add_db
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("C4_ChauSolution.Models.Cart", b =>
                {
                    b.Property<Guid>("IdKH")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("IdKH");

                    b.ToTable("Cart", (string)null);
                });

            modelBuilder.Entity("C4_ChauSolution.Models.CartDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdChiTietSP")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdKH")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int")
                        .HasColumnName("SoLuong");

                    b.HasKey("Id");

                    b.HasIndex("IdChiTietSP");

                    b.HasIndex("IdKH");

                    b.ToTable("CartDetail", (string)null);
                });

            modelBuilder.Entity("C4_ChauSolution.Models.ChiTietHoaDon", b =>
                {
                    b.Property<Guid>("IdCTHoaDon")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal")
                        .HasColumnName("DonGia");

                    b.Property<Guid>("IdChiTietSP")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdHoaDon")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("SoLuongMua")
                        .HasColumnType("decimal")
                        .HasColumnName("SoLuongMua");

                    b.HasKey("IdCTHoaDon");

                    b.HasIndex("IdChiTietSP");

                    b.ToTable("ChiTietHoaDon", (string)null);
                });

            modelBuilder.Entity("C4_ChauSolution.Models.ChiTietSanPham", b =>
                {
                    b.Property<Guid>("IdChiTietSP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("decimal")
                        .HasColumnName("GiaBan");

                    b.Property<decimal>("GiaNhap")
                        .HasColumnType("decimal")
                        .HasColumnName("GiaNhap");

                    b.Property<byte[]>("HinhAnh")
                        .IsRequired()
                        .HasColumnType("image")
                        .HasColumnName("HinhAnh");

                    b.Property<Guid>("IdDanhMuc")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdDonVi")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdLoaiSp")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdNhaCungCap")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdSp")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("SoLuong")
                        .HasColumnType("decimal")
                        .HasColumnName("SoLuong");

                    b.HasKey("IdChiTietSP");

                    b.HasIndex("IdDanhMuc");

                    b.HasIndex("IdDonVi");

                    b.HasIndex("IdLoaiSp");

                    b.HasIndex("IdSp");

                    b.ToTable("ChiTietSP", (string)null);
                });

            modelBuilder.Entity("C4_ChauSolution.Models.DanhMuc", b =>
                {
                    b.Property<Guid>("IdDanhMuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenDanhMuc");

                    b.HasKey("IdDanhMuc");

                    b.ToTable("DanhMuc", (string)null);
                });

            modelBuilder.Entity("C4_ChauSolution.Models.DonVi", b =>
                {
                    b.Property<Guid>("IdDonVi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenDonVi")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TenDonVi");

                    b.HasKey("IdDonVi");

                    b.ToTable("DonVi", (string)null);
                });

            modelBuilder.Entity("C4_ChauSolution.Models.HoaDon", b =>
                {
                    b.Property<Guid>("IdHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdNhanVien")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime")
                        .HasColumnName("NgayTao");

                    b.Property<DateTime>("NgayThanhToan")
                        .HasColumnType("datetime")
                        .HasColumnName("NgayThanhToan");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal")
                        .HasColumnName("TongTien");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int")
                        .HasColumnName("TrangThai");

                    b.HasKey("IdHoaDon");

                    b.HasIndex("IdNhanVien");

                    b.ToTable("HoaDon", (string)null);
                });

            modelBuilder.Entity("C4_ChauSolution.Models.KhachHang", b =>
                {
                    b.Property<Guid>("IdKH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ĐiaChi");

                    b.Property<int>("GioiTinh")
                        .HasColumnType("int")
                        .HasColumnName("GioiTinh");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("SDT");

                    b.Property<string>("TenKh")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenKhachHang");

                    b.HasKey("IdKH");

                    b.ToTable("KhachHang", (string)null);
                });

            modelBuilder.Entity("C4_ChauSolution.Models.LoaiSp", b =>
                {
                    b.Property<Guid>("IdLoaiSp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenLoaiSp")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenLoaiSp");

                    b.HasKey("IdLoaiSp");

                    b.ToTable("LoaiSanPham", (string)null);
                });

            modelBuilder.Entity("C4_ChauSolution.Models.NhaCungCap", b =>
                {
                    b.Property<Guid>("IdNhaCungCap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenNhaCungCap")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenNhaCC");

                    b.HasKey("IdNhaCungCap");

                    b.ToTable("NhaCungCap", (string)null);
                });

            modelBuilder.Entity("C4_ChauSolution.Models.NhanVien", b =>
                {
                    b.Property<Guid>("IdNhanVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ĐiaChi");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Email");

                    b.Property<bool>("GioiTinh")
                        .HasColumnType("bit")
                        .HasColumnName("GioiTinh");

                    b.Property<bool>("IdLoaiTk")
                        .HasColumnType("bit")
                        .HasColumnName("IdLoaiTk");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MatKhau");

                    b.Property<DateTime>("NamSinh")
                        .HasColumnType("datetime")
                        .HasColumnName("NamSinh");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("SĐT");

                    b.Property<string>("TenNv")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenNhanVien");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit")
                        .HasColumnName("TrangThaiTK");

                    b.Property<bool>("TrangThaiPass")
                        .HasColumnType("bit")
                        .HasColumnName("TrangThaiPass");

                    b.HasKey("IdNhanVien");

                    b.ToTable("NhanVien", (string)null);
                });

            modelBuilder.Entity("C4_ChauSolution.Models.SanPham", b =>
                {
                    b.Property<Guid>("IdSp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenSp")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenSanPham");

                    b.HasKey("IdSp");

                    b.ToTable("SanPham", (string)null);
                });

            modelBuilder.Entity("C4_ChauSolution.Models.Cart", b =>
                {
                    b.HasOne("C4_ChauSolution.Models.KhachHang", "KhachHangs")
                        .WithOne("Carts")
                        .HasForeignKey("C4_ChauSolution.Models.Cart", "IdKH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHangs");
                });

            modelBuilder.Entity("C4_ChauSolution.Models.CartDetail", b =>
                {
                    b.HasOne("C4_ChauSolution.Models.ChiTietSanPham", "ChiTietSanPham")
                        .WithMany("CartDetails")
                        .HasForeignKey("IdChiTietSP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("C4_ChauSolution.Models.Cart", "Cart")
                        .WithMany("CartDetails")
                        .HasForeignKey("IdKH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("ChiTietSanPham");
                });

            modelBuilder.Entity("C4_ChauSolution.Models.ChiTietHoaDon", b =>
                {
                    b.HasOne("C4_ChauSolution.Models.HoaDon", "HoaDon")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("IdCTHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("C4_ChauSolution.Models.ChiTietSanPham", "ChiTietSanPham")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("IdChiTietSP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChiTietSanPham");

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("C4_ChauSolution.Models.ChiTietSanPham", b =>
                {
                    b.HasOne("C4_ChauSolution.Models.DanhMuc", "DanhMuc")
                        .WithMany("ChiTietSanPhams")
                        .HasForeignKey("IdDanhMuc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("C4_ChauSolution.Models.DonVi", "DonVi")
                        .WithMany("ChiTietSanPhams")
                        .HasForeignKey("IdDonVi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("C4_ChauSolution.Models.NhaCungCap", "NhaCungCap")
                        .WithMany("ChiTietSanPhams")
                        .HasForeignKey("IdDonVi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("C4_ChauSolution.Models.LoaiSp", "LoaiSp")
                        .WithMany("ChiTietSanPhams")
                        .HasForeignKey("IdLoaiSp")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("C4_ChauSolution.Models.SanPham", "SanPham")
                        .WithMany("ChiTietSanPhams")
                        .HasForeignKey("IdSp")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DanhMuc");

                    b.Navigation("DonVi");

                    b.Navigation("LoaiSp");

                    b.Navigation("NhaCungCap");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("C4_ChauSolution.Models.HoaDon", b =>
                {
                    b.HasOne("C4_ChauSolution.Models.NhanVien", "NhanVien")
                        .WithMany("HoaDons")
                        .HasForeignKey("IdNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("C4_ChauSolution.Models.Cart", b =>
                {
                    b.Navigation("CartDetails");
                });

            modelBuilder.Entity("C4_ChauSolution.Models.ChiTietSanPham", b =>
                {
                    b.Navigation("CartDetails");

                    b.Navigation("ChiTietHoaDons");
                });

            modelBuilder.Entity("C4_ChauSolution.Models.DanhMuc", b =>
                {
                    b.Navigation("ChiTietSanPhams");
                });

            modelBuilder.Entity("C4_ChauSolution.Models.DonVi", b =>
                {
                    b.Navigation("ChiTietSanPhams");
                });

            modelBuilder.Entity("C4_ChauSolution.Models.HoaDon", b =>
                {
                    b.Navigation("ChiTietHoaDons");
                });

            modelBuilder.Entity("C4_ChauSolution.Models.KhachHang", b =>
                {
                    b.Navigation("Carts")
                        .IsRequired();
                });

            modelBuilder.Entity("C4_ChauSolution.Models.LoaiSp", b =>
                {
                    b.Navigation("ChiTietSanPhams");
                });

            modelBuilder.Entity("C4_ChauSolution.Models.NhaCungCap", b =>
                {
                    b.Navigation("ChiTietSanPhams");
                });

            modelBuilder.Entity("C4_ChauSolution.Models.NhanVien", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("C4_ChauSolution.Models.SanPham", b =>
                {
                    b.Navigation("ChiTietSanPhams");
                });
#pragma warning restore 612, 618
        }
    }
}
