// <auto-generated />
using System;
using C4_ChauSolution.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace C4_ChauSolution.Migrations
{
    [DbContext(typeof(VatLieuDbContext))]
    [Migration("20230321152320_Updater_DBB")]
    partial class Updater_DBB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("C4_ChauSolution.Models.Cart", b =>
                {
                    b.Property<Guid>("IdKH")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("IdKH");

                    b.ToTable("Cart", (string)null);
                });

            modelBuilder.Entity("C4_ChauSolution.Models.CartDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdChiTietSP")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdKH")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int")
                        .HasColumnName("SoLuong");

                    b.HasKey("Id");

                    b.HasIndex("IdChiTietSP");

                    b.HasIndex("IdKH");

                    b.ToTable("CartDetail", (string)null);
                });

            modelBuilder.Entity("C4_ChauSolution.Models.ChiTietHoaDon", b =>
                {
                    b.Property<Guid>("IdCTHoaDon")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal")
                        .HasColumnName("DonGia");

                    b.Property<Guid>("IdChiTietSP")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdHoaDon")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("SoLuongMua")
                        .HasColumnType("decimal")
                        .HasColumnName("SoLuongMua");

                    b.HasKey("IdCTHoaDon");

                    b.HasIndex("IdChiTietSP");

                    b.ToTable("ChiTietHoaDon", (string)null);
                });

            modelBuilder.Entity("C4_ChauSolution.Models.ChiTietSanPham", b =>
                {
                    b.Property<Guid>("IdChiTietSP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("decimal")
                        .HasColumnName("GiaBan");

                    b.Property<decimal>("GiaNhap")
                        .HasColumnType("decimal")
                        .HasColumnName("GiaNhap");

                    b.Property<byte[]>("HinhAnh")
                        .IsRequired()
                        .HasColumnType("image")
                        .HasColumnName("HinhAnh");

                    b.Property<decimal>("SoLuong")
                        .HasColumnType("decimal")
                        .HasColumnName("SoLuong");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDonVi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenLoaiSp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNhaCungCap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenSp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdChiTietSP");

                    b.ToTable("ChiTietSP", (string)null);
                });

            modelBuilder.Entity("C4_ChauSolution.Models.HoaDon", b =>
                {
                    b.Property<Guid>("IdHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdNhanVien")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime")
                        .HasColumnName("NgayTao");

                    b.Property<DateTime>("NgayThanhToan")
                        .HasColumnType("datetime")
                        .HasColumnName("NgayThanhToan");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal")
                        .HasColumnName("TongTien");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int")
                        .HasColumnName("TrangThai");

                    b.HasKey("IdHoaDon");

                    b.HasIndex("IdNhanVien");

                    b.ToTable("HoaDon", (string)null);
                });

            modelBuilder.Entity("C4_ChauSolution.Models.KhachHang", b =>
                {
                    b.Property<Guid>("IdKH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ĐiaChi");

                    b.Property<int>("GioiTinh")
                        .HasColumnType("int")
                        .HasColumnName("GioiTinh");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("SDT");

                    b.Property<string>("TenKh")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenKhachHang");

                    b.HasKey("IdKH");

                    b.ToTable("KhachHang", (string)null);
                });

            modelBuilder.Entity("C4_ChauSolution.Models.NhanVien", b =>
                {
                    b.Property<Guid>("IdNhanVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ĐiaChi");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Email");

                    b.Property<bool>("GioiTinh")
                        .HasColumnType("bit")
                        .HasColumnName("GioiTinh");

                    b.Property<bool>("IdLoaiTk")
                        .HasColumnType("bit")
                        .HasColumnName("IdLoaiTk");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MatKhau");

                    b.Property<DateTime>("NamSinh")
                        .HasColumnType("datetime")
                        .HasColumnName("NamSinh");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("SĐT");

                    b.Property<string>("TenNv")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenNhanVien");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit")
                        .HasColumnName("TrangThaiTK");

                    b.Property<bool>("TrangThaiPass")
                        .HasColumnType("bit")
                        .HasColumnName("TrangThaiPass");

                    b.HasKey("IdNhanVien");

                    b.ToTable("NhanVien", (string)null);
                });

            modelBuilder.Entity("C4_ChauSolution.Models.Cart", b =>
                {
                    b.HasOne("C4_ChauSolution.Models.KhachHang", "KhachHangs")
                        .WithOne("Carts")
                        .HasForeignKey("C4_ChauSolution.Models.Cart", "IdKH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHangs");
                });

            modelBuilder.Entity("C4_ChauSolution.Models.CartDetail", b =>
                {
                    b.HasOne("C4_ChauSolution.Models.ChiTietSanPham", "ChiTietSanPham")
                        .WithMany("CartDetails")
                        .HasForeignKey("IdChiTietSP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("C4_ChauSolution.Models.Cart", "Cart")
                        .WithMany("CartDetails")
                        .HasForeignKey("IdKH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("ChiTietSanPham");
                });

            modelBuilder.Entity("C4_ChauSolution.Models.ChiTietHoaDon", b =>
                {
                    b.HasOne("C4_ChauSolution.Models.HoaDon", "HoaDon")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("IdCTHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("C4_ChauSolution.Models.ChiTietSanPham", "ChiTietSanPham")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("IdChiTietSP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChiTietSanPham");

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("C4_ChauSolution.Models.HoaDon", b =>
                {
                    b.HasOne("C4_ChauSolution.Models.NhanVien", "NhanVien")
                        .WithMany("HoaDons")
                        .HasForeignKey("IdNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("C4_ChauSolution.Models.Cart", b =>
                {
                    b.Navigation("CartDetails");
                });

            modelBuilder.Entity("C4_ChauSolution.Models.ChiTietSanPham", b =>
                {
                    b.Navigation("CartDetails");

                    b.Navigation("ChiTietHoaDons");
                });

            modelBuilder.Entity("C4_ChauSolution.Models.HoaDon", b =>
                {
                    b.Navigation("ChiTietHoaDons");
                });

            modelBuilder.Entity("C4_ChauSolution.Models.KhachHang", b =>
                {
                    b.Navigation("Carts")
                        .IsRequired();
                });

            modelBuilder.Entity("C4_ChauSolution.Models.NhanVien", b =>
                {
                    b.Navigation("HoaDons");
                });
#pragma warning restore 612, 618
        }
    }
}
